export const automationTriggers = {
  triggers: {
    Lead: [
      {
        displayName: "New Lead",
        actName: "Lead Created",
        actType: "Event",
        category: "Lead",
        description: "When a new Lead is created or added",
      },
      {
        displayName: "Lead Update",
        actName: "Lead Updated",
        actType: "Event",
        category: "Lead",
        description: "When a Lead field is updated or changed",
      },
      {
        displayName: "Lead Added to List",
        actName: "Lead Added To List",
        actType: "Event",
        category: "Lead",
        description: "When a Lead is added to a static list",
      },
      {
        displayName: "On a Specific Date",
        actName: "On Specific Date",
        actType: "Event",
        category: "Lead",
        description: "Such as birthday, renewal date etc.",
      },
    ],
    Opportunity: [
      {
        displayName: "New Opportunity on Lead",
        actName: "On Opportunity Added",
        actType: "Event",
        category: "Opportunity",
        description: "When a new opportunity is created or added for Lead",
      },
      {
        displayName: "Opportunity Update on Lead",
        actName: "On Opportunity Updated",
        actType: "Event",
        category: "Opportunity",
        description: "When an opportunity field is updated or changed.",
      },
      {
        displayName: "On a Specific Date",
        actName: "On Specific Date For Opportunity",
        actType: "Event",
        category: "Opportunity",
        description: "Such as birthday, renewal date etc. for opportunity",
      },
    ],
    Activity: [
      {
        displayName: "New Activity on Lead",
        actName: "On Activity Added",
        actType: "Event",
        category: "Activity",
        description: "Such as Form Submission, Page Visit etc.",
      },
      {
        displayName: "Activity Update on Lead",
        actName: "On Activity Updated",
        actType: "Event",
        category: "Activity",
        description: "Such as Sales Activity etc.",
      },
      {
        displayName: "New Activity On Opportunity",
        actName: "On Opportunity Activity Added",
        actType: "Event",
        category: "Activity",
        description: "When an opportunity activity is added",
      },
      {
        displayName: "Activity Update On Opportunity",
        actName: "On Opportunity Activity Updated",
        actType: "Event",
        category: "Activity",
        description: "When an opportunity activity is updated",
      },
      {
        displayName: "New Activity On Activity",
        actName: "On Activity on Activity Added",
        actType: "Event",
        category: "Activity",
        description: "Such as Service Ticket etc.",
      },
      {
        displayName: "Activity Update On Activity",
        actName: "On Activity on Activity Updated",
        actType: "Event",
        category: "Activity",
        description: "Such as Service Ticket etc.",
      },
    ],
    User: [
      {
        displayName: "On a Specific Date",
        actName: "On Specific Date",
        actType: "Event",
        category: "User",
        description: "Such as User's birthday, joining date etc",
      },
      {
        displayName: "Start of a Work Day",
        actName: "On WorkDay Start",
        actType: "Event",
        category: "User",
        description: "When a user begins their work day shift",
      },
      {
        displayName: "End of a Work Day",
        actName: "On WorkDay End",
        actType: "Event",
        category: "User",
        description: "When a user ends their work day shift",
      },
    ],
    Task: [
      {
        displayName: "Task Create",
        actName: "Task Create",
        actType: "Event",
        category: "Task",
        description: "When a new task is created or added on Lead",
      },
      {
        displayName: "Task Reminder",
        actName: "Task Reminder",
        actType: "Event",
        category: "Task",
        description: "On task reminder",
      },
      {
        displayName: "Task Updated on Lead",
        actName: "Task Update",
        actType: "Event",
        category: "Task",
        description: "When a task is updated on Lead",
      },
      {
        displayName: "Task Complete",
        actName: "Task Complete",
        actType: "Event",
        category: "Task",
        description: "When a task is completed on Lead",
      },
      {
        displayName: "Task Created on Opportunity",
        actName: "On Opportunity Task Create",
        actType: "Event",
        category: "Task",
        description: "When a task is created on an opportunity",
      },
      {
        displayName: "Task Updated on Opportunity",
        actName: "On Opportunity Task Update",
        actType: "Event",
        category: "Task",
        description: "When a task is updated on an Opportunity",
      },
      {
        displayName: "Task Completed on Opportunity",
        actName: "On Opportunity Task Complete",
        actType: "Event",
        category: "Task",
        description: "When a task is completed on an opportunity",
      },
      {
        displayName: "Task Reminder for Opportunity",
        actName: "On Opportunity Task Reminder",
        actType: "Event",
        category: "Task",
        description: "On task reminder",
      },
    ],
    Cron: [
      {
        displayName: "At Regular Intervals",
        actName: "At Regular Intervals",
        actType: "Event",
        category: "Cron",
        description: "Such as every hour, day, week or month etc",
      },
    ],
  },
};
