import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { PageHeader, Card, StatCard, Badge } from "@/components/ui-kit";
import { sourceMix, monthlyTrend } from "@/lib/mock-data";
import { Megaphone, TrendingDown, MousePointerClick, Workflow, Plus, Sparkles } from "lucide-react";
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  LineChart,
  Line,
} from "recharts";

export const Route = createFileRoute("/marketing")({
  component: MarketingPage,
  head: () => ({ meta: [{ title: "Marketing Automation — Acharya One" }] }),
});

const campaigns = [
  {
    name: "BTech_Karnataka_Q2",
    channel: "Google Ads",
    spend: 480000,
    leads: 1240,
    cpl: 387,
    conv: 8.4,
    status: "Active",
  },
  {
    name: "MBA_Reels_Apr",
    channel: "Meta Ads",
    spend: 320000,
    leads: 980,
    cpl: 326,
    conv: 6.2,
    status: "Active",
  },
  {
    name: "International_UAE",
    channel: "Google Ads",
    spend: 220000,
    leads: 412,
    cpl: 534,
    conv: 11.2,
    status: "Active",
  },
  {
    name: "Scholarship_Drive",
    channel: "Email/WA",
    spend: 24000,
    leads: 624,
    cpl: 38,
    conv: 14.8,
    status: "Active",
  },
  {
    name: "OpenHouse_BLR",
    channel: "Outdoor",
    spend: 180000,
    leads: 280,
    cpl: 642,
    conv: 18.6,
    status: "Paused",
  },
];

function MarketingPage() {
  return (
    <AppShell>
      <PageHeader
        breadcrumb="Growth"
        title="Marketing Automation"
        subtitle="Campaigns, attribution, journey builder and AI-driven nurture."
        actions={
          <>
            <button className="rounded-lg border border-border bg-card px-3 h-9 text-[13px] font-medium flex items-center gap-1.5">
              <Workflow className="size-4" /> Journey Builder
            </button>
            <button className="rounded-lg bg-primary text-primary-foreground px-3 h-9 text-[13px] font-semibold flex items-center gap-1.5">
              <Plus className="size-4" /> New Campaign
            </button>
          </>
        }
      />

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <StatCard
          label="Total Spend MTD"
          value="₹34.2L"
          delta="+8.2%"
          icon={<Megaphone className="size-4" />}
        />
        <StatCard
          label="Leads Generated"
          value="8,140"
          delta="+22%"
          icon={<MousePointerClick className="size-4" />}
          accent="success"
        />
        <StatCard
          label="Avg CPL"
          value="₹421"
          delta="-12%"
          icon={<TrendingDown className="size-4" />}
          accent="info"
        />
        <StatCard
          label="Marketing ROI"
          value="6.8x"
          delta="+1.4x"
          icon={<Sparkles className="size-4" />}
          accent="gold"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
        <Card className="p-5 lg:col-span-2">
          <h3 className="font-display font-semibold text-[15px] mb-1">Channel Performance</h3>
          <p className="text-xs text-muted-foreground mb-3">Spend vs leads generated by source</p>
          <div className="h-64">
            <ResponsiveContainer>
              <BarChart
                data={sourceMix.map((s) => ({
                  name: s.name,
                  spend: s.cost / 1000,
                  leads: s.value * 50,
                }))}
                margin={{ left: -10 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} />
                <XAxis dataKey="name" fontSize={11} tickLine={false} axisLine={false} />
                <YAxis fontSize={11} tickLine={false} axisLine={false} />
                <Tooltip
                  contentStyle={{
                    borderRadius: 8,
                    border: "1px solid oklch(0.92 0.01 255)",
                    fontSize: 12,
                  }}
                />
                <Bar dataKey="spend" fill="oklch(0.55 0.22 264)" radius={[6, 6, 0, 0]} />
                <Bar dataKey="leads" fill="oklch(0.76 0.15 75)" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Card>

        <Card className="p-5 bg-gradient-to-br from-card to-primary-soft/30">
          <div className="flex items-center gap-2 mb-3">
            <div className="size-7 rounded-md bg-gradient-aurora grid place-items-center">
              <Sparkles className="size-4 text-white" />
            </div>
            <h3 className="font-display font-semibold text-[15px]">AI Recommendations</h3>
          </div>
          <div className="space-y-2.5 text-[13px]">
            {[
              {
                t: "Increase Meta Ads budget by 30%",
                d: "CPL down 18%, conversion up 4pp",
                tone: "success" as const,
              },
              {
                t: "Pause OpenHouse_BLR",
                d: "CPL 4× higher than channel avg",
                tone: "danger" as const,
              },
              {
                t: "Launch UAE retargeting",
                d: "+42% inquiries, no nurture flow",
                tone: "info" as const,
              },
              {
                t: "A/B test scholarship subject lines",
                d: "Open rate ceiling at 22%",
                tone: "warning" as const,
              },
            ].map((r, i) => (
              <div key={i} className="p-3 rounded-lg bg-card border border-border">
                <div className="flex items-start gap-2">
                  <Badge tone={r.tone}>AI</Badge>
                  <div className="flex-1">
                    <div className="font-semibold leading-tight">{r.t}</div>
                    <div className="text-[12px] text-muted-foreground mt-0.5">{r.d}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      <Card className="overflow-hidden">
        <div className="px-5 py-3 border-b border-border">
          <h3 className="font-display font-semibold text-[15px]">Live Campaigns</h3>
        </div>
        <table className="w-full text-[13px]">
          <thead className="bg-muted/40 text-muted-foreground">
            <tr className="text-left">
              {["Campaign", "Channel", "Spend", "Leads", "CPL", "Conv %", "Status"].map((h) => (
                <th
                  key={h}
                  className="px-4 py-2.5 font-semibold text-[11px] uppercase tracking-wider"
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {campaigns.map((c) => (
              <tr key={c.name} className="hover:bg-muted/40">
                <td className="px-4 py-3 font-semibold">{c.name}</td>
                <td className="px-4 py-3">
                  <Badge tone="info">{c.channel}</Badge>
                </td>
                <td className="px-4 py-3 font-semibold tabular-nums">
                  ₹{(c.spend / 1000).toFixed(0)}K
                </td>
                <td className="px-4 py-3 tabular-nums">{c.leads.toLocaleString()}</td>
                <td className="px-4 py-3 font-bold tabular-nums">₹{c.cpl}</td>
                <td className="px-4 py-3">
                  <span className="font-bold text-success tabular-nums">{c.conv}%</span>
                </td>
                <td className="px-4 py-3">
                  <Badge tone={c.status === "Active" ? "success" : "muted"}>{c.status}</Badge>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>

      <Card className="p-5 mt-6 ">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-display font-semibold text-[15px]">Lead Nurture Journey</h3>
          <Badge tone="primary">3 active flows</Badge>
        </div>
        <div className="overflow-x-auto scrollbar-thin pb-2">
          <div className="flex items-stretch gap-2 min-w-max">
            {[
              { t: "Trigger", d: "Lead inquiry form", tone: "primary" },
              { t: "Wait", d: "10 minutes" },
              { t: "WhatsApp", d: "Welcome + counsellor intro", tone: "success" },
              { t: "Wait", d: "1 day" },
              { t: "Email", d: "Brochure + program details", tone: "info" },
              { t: "Branch", d: "If opened → call task" },
              { t: "WhatsApp", d: "Scholarship eligibility quiz", tone: "success" },
              { t: "Goal", d: "Application started", tone: "gold" },
            ].map((s, i) => (
              <div key={i} className="flex items-center gap-2">
                <div
                  className={`w-44 rounded-xl border-2 border-dashed p-3 ${s.tone ? "border-primary/30 bg-primary-soft/30" : "border-border bg-muted/30"}`}
                >
                  <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
                    {s.t}
                  </div>
                  <div className="text-[13px] font-semibold mt-1">{s.d}</div>
                </div>
                {i < 7 && <div className="text-muted-foreground">→</div>}
              </div>
            ))}
          </div>
        </div>
      </Card>
    </AppShell>
  );
}
