/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CounsellorRouteImport } from './routes/counsellor'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as ChatSettingsRouteImport } from './routes/chat-settings'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcharyawebsiteRouteImport } from './routes/acharyawebsite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as OfferIndexRouteImport } from './routes/offer.index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as EnrollmentIndexRouteImport } from './routes/enrollment.index'
import { Route as EmailTemplatesIndexRouteImport } from './routes/email-templates.index'
import { Route as AutomationIndexRouteImport } from './routes/automation.index'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as ProgramsNewRouteImport } from './routes/programs.new'
import { Route as OfferOfferIdRouteImport } from './routes/offer.$offerId'
import { Route as ListsListIdRouteImport } from './routes/lists.$listId'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as EnrollmentEnrollmentIdRouteImport } from './routes/enrollment.$enrollmentId'
import { Route as AutomationAutomationIdRouteImport } from './routes/automation.$automationId'
import { Route as ApplicationStartRouteImport } from './routes/application.start'
import { Route as ApplicationApplicationIdRouteImport } from './routes/application.$applicationId'
import { Route as EmailTemplatesCreateVisualRouteImport } from './routes/email-templates.create.visual'
import { Route as EmailTemplatesCreateRichTextRouteImport } from './routes/email-templates.create.rich-text'
import { Route as EmailTemplatesCreatePlainTextRouteImport } from './routes/email-templates.create.plain-text'
import { Route as EmailTemplatesCreateHtmlRouteImport } from './routes/email-templates.create.html'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorRoute = CounsellorRouteImport.update({
  id: '/counsellor',
  path: '/counsellor',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/chat-settings',
  path: '/chat-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcharyawebsiteRoute = AcharyawebsiteRouteImport.update({
  id: '/acharyawebsite',
  path: '/acharyawebsite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferIndexRoute = OfferIndexRouteImport.update({
  id: '/offer/',
  path: '/offer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentIndexRoute = EnrollmentIndexRouteImport.update({
  id: '/enrollment/',
  path: '/enrollment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesIndexRoute = EmailTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmailTemplatesRoute,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutomationRoute,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsNewRoute = ProgramsNewRouteImport.update({
  id: '/programs/new',
  path: '/programs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferOfferIdRoute = OfferOfferIdRouteImport.update({
  id: '/offer/$offerId',
  path: '/offer/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentEnrollmentIdRoute = EnrollmentEnrollmentIdRouteImport.update({
  id: '/enrollment/$enrollmentId',
  path: '/enrollment/$enrollmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationAutomationIdRoute = AutomationAutomationIdRouteImport.update({
  id: '/$automationId',
  path: '/$automationId',
  getParentRoute: () => AutomationRoute,
} as any)
const ApplicationStartRoute = ApplicationStartRouteImport.update({
  id: '/application/start',
  path: '/application/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationApplicationIdRoute =
  ApplicationApplicationIdRouteImport.update({
    id: '/application/$applicationId',
    path: '/application/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmailTemplatesCreateVisualRoute =
  EmailTemplatesCreateVisualRouteImport.update({
    id: '/create/visual',
    path: '/create/visual',
    getParentRoute: () => EmailTemplatesRoute,
  } as any)
const EmailTemplatesCreateRichTextRoute =
  EmailTemplatesCreateRichTextRouteImport.update({
    id: '/create/rich-text',
    path: '/create/rich-text',
    getParentRoute: () => EmailTemplatesRoute,
  } as any)
const EmailTemplatesCreatePlainTextRoute =
  EmailTemplatesCreatePlainTextRouteImport.update({
    id: '/create/plain-text',
    path: '/create/plain-text',
    getParentRoute: () => EmailTemplatesRoute,
  } as any)
const EmailTemplatesCreateHtmlRoute =
  EmailTemplatesCreateHtmlRouteImport.update({
    id: '/create/html',
    path: '/create/html',
    getParentRoute: () => EmailTemplatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acharyawebsite': typeof AcharyawebsiteRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/automation': typeof AutomationRouteWithChildren
  '/chat-settings': typeof ChatSettingsRoute
  '/communications': typeof CommunicationsRoute
  '/counsellor': typeof CounsellorRoute
  '/dashboard': typeof DashboardRoute
  '/distribution': typeof DistributionRoute
  '/email-templates': typeof EmailTemplatesRouteWithChildren
  '/finance': typeof FinanceRoute
  '/international': typeof InternationalRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/partners': typeof PartnersRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/tasks': typeof TasksRoute
  '/verification': typeof VerificationRoute
  '/application/$applicationId': typeof ApplicationApplicationIdRoute
  '/application/start': typeof ApplicationStartRoute
  '/automation/$automationId': typeof AutomationAutomationIdRoute
  '/enrollment/$enrollmentId': typeof EnrollmentEnrollmentIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/offer/$offerId': typeof OfferOfferIdRoute
  '/programs/new': typeof ProgramsNewRoute
  '/users/new': typeof UsersNewRoute
  '/automation/': typeof AutomationIndexRoute
  '/email-templates/': typeof EmailTemplatesIndexRoute
  '/enrollment/': typeof EnrollmentIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/offer/': typeof OfferIndexRoute
  '/users/': typeof UsersIndexRoute
  '/email-templates/create/html': typeof EmailTemplatesCreateHtmlRoute
  '/email-templates/create/plain-text': typeof EmailTemplatesCreatePlainTextRoute
  '/email-templates/create/rich-text': typeof EmailTemplatesCreateRichTextRoute
  '/email-templates/create/visual': typeof EmailTemplatesCreateVisualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acharyawebsite': typeof AcharyawebsiteRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/chat-settings': typeof ChatSettingsRoute
  '/communications': typeof CommunicationsRoute
  '/counsellor': typeof CounsellorRoute
  '/dashboard': typeof DashboardRoute
  '/distribution': typeof DistributionRoute
  '/finance': typeof FinanceRoute
  '/international': typeof InternationalRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/partners': typeof PartnersRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/tasks': typeof TasksRoute
  '/verification': typeof VerificationRoute
  '/application/$applicationId': typeof ApplicationApplicationIdRoute
  '/application/start': typeof ApplicationStartRoute
  '/automation/$automationId': typeof AutomationAutomationIdRoute
  '/enrollment/$enrollmentId': typeof EnrollmentEnrollmentIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/offer/$offerId': typeof OfferOfferIdRoute
  '/programs/new': typeof ProgramsNewRoute
  '/users/new': typeof UsersNewRoute
  '/automation': typeof AutomationIndexRoute
  '/email-templates': typeof EmailTemplatesIndexRoute
  '/enrollment': typeof EnrollmentIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/lists': typeof ListsIndexRoute
  '/offer': typeof OfferIndexRoute
  '/users': typeof UsersIndexRoute
  '/email-templates/create/html': typeof EmailTemplatesCreateHtmlRoute
  '/email-templates/create/plain-text': typeof EmailTemplatesCreatePlainTextRoute
  '/email-templates/create/rich-text': typeof EmailTemplatesCreateRichTextRoute
  '/email-templates/create/visual': typeof EmailTemplatesCreateVisualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acharyawebsite': typeof AcharyawebsiteRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/automation': typeof AutomationRouteWithChildren
  '/chat-settings': typeof ChatSettingsRoute
  '/communications': typeof CommunicationsRoute
  '/counsellor': typeof CounsellorRoute
  '/dashboard': typeof DashboardRoute
  '/distribution': typeof DistributionRoute
  '/email-templates': typeof EmailTemplatesRouteWithChildren
  '/finance': typeof FinanceRoute
  '/international': typeof InternationalRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/partners': typeof PartnersRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/tasks': typeof TasksRoute
  '/verification': typeof VerificationRoute
  '/application/$applicationId': typeof ApplicationApplicationIdRoute
  '/application/start': typeof ApplicationStartRoute
  '/automation/$automationId': typeof AutomationAutomationIdRoute
  '/enrollment/$enrollmentId': typeof EnrollmentEnrollmentIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/offer/$offerId': typeof OfferOfferIdRoute
  '/programs/new': typeof ProgramsNewRoute
  '/users/new': typeof UsersNewRoute
  '/automation/': typeof AutomationIndexRoute
  '/email-templates/': typeof EmailTemplatesIndexRoute
  '/enrollment/': typeof EnrollmentIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/offer/': typeof OfferIndexRoute
  '/users/': typeof UsersIndexRoute
  '/email-templates/create/html': typeof EmailTemplatesCreateHtmlRoute
  '/email-templates/create/plain-text': typeof EmailTemplatesCreatePlainTextRoute
  '/email-templates/create/rich-text': typeof EmailTemplatesCreateRichTextRoute
  '/email-templates/create/visual': typeof EmailTemplatesCreateVisualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acharyawebsite'
    | '/admissions'
    | '/analytics'
    | '/applications'
    | '/automation'
    | '/chat-settings'
    | '/communications'
    | '/counsellor'
    | '/dashboard'
    | '/distribution'
    | '/email-templates'
    | '/finance'
    | '/international'
    | '/login'
    | '/marketing'
    | '/partners'
    | '/scholarships'
    | '/settings'
    | '/student'
    | '/tasks'
    | '/verification'
    | '/application/$applicationId'
    | '/application/start'
    | '/automation/$automationId'
    | '/enrollment/$enrollmentId'
    | '/leads/$leadId'
    | '/leads/new'
    | '/lists/$listId'
    | '/offer/$offerId'
    | '/programs/new'
    | '/users/new'
    | '/automation/'
    | '/email-templates/'
    | '/enrollment/'
    | '/leads/'
    | '/lists/'
    | '/offer/'
    | '/users/'
    | '/email-templates/create/html'
    | '/email-templates/create/plain-text'
    | '/email-templates/create/rich-text'
    | '/email-templates/create/visual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acharyawebsite'
    | '/admissions'
    | '/analytics'
    | '/applications'
    | '/chat-settings'
    | '/communications'
    | '/counsellor'
    | '/dashboard'
    | '/distribution'
    | '/finance'
    | '/international'
    | '/login'
    | '/marketing'
    | '/partners'
    | '/scholarships'
    | '/settings'
    | '/student'
    | '/tasks'
    | '/verification'
    | '/application/$applicationId'
    | '/application/start'
    | '/automation/$automationId'
    | '/enrollment/$enrollmentId'
    | '/leads/$leadId'
    | '/leads/new'
    | '/lists/$listId'
    | '/offer/$offerId'
    | '/programs/new'
    | '/users/new'
    | '/automation'
    | '/email-templates'
    | '/enrollment'
    | '/leads'
    | '/lists'
    | '/offer'
    | '/users'
    | '/email-templates/create/html'
    | '/email-templates/create/plain-text'
    | '/email-templates/create/rich-text'
    | '/email-templates/create/visual'
  id:
    | '__root__'
    | '/'
    | '/acharyawebsite'
    | '/admissions'
    | '/analytics'
    | '/applications'
    | '/automation'
    | '/chat-settings'
    | '/communications'
    | '/counsellor'
    | '/dashboard'
    | '/distribution'
    | '/email-templates'
    | '/finance'
    | '/international'
    | '/login'
    | '/marketing'
    | '/partners'
    | '/scholarships'
    | '/settings'
    | '/student'
    | '/tasks'
    | '/verification'
    | '/application/$applicationId'
    | '/application/start'
    | '/automation/$automationId'
    | '/enrollment/$enrollmentId'
    | '/leads/$leadId'
    | '/leads/new'
    | '/lists/$listId'
    | '/offer/$offerId'
    | '/programs/new'
    | '/users/new'
    | '/automation/'
    | '/email-templates/'
    | '/enrollment/'
    | '/leads/'
    | '/lists/'
    | '/offer/'
    | '/users/'
    | '/email-templates/create/html'
    | '/email-templates/create/plain-text'
    | '/email-templates/create/rich-text'
    | '/email-templates/create/visual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcharyawebsiteRoute: typeof AcharyawebsiteRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AutomationRoute: typeof AutomationRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  CounsellorRoute: typeof CounsellorRoute
  DashboardRoute: typeof DashboardRoute
  DistributionRoute: typeof DistributionRoute
  EmailTemplatesRoute: typeof EmailTemplatesRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  InternationalRoute: typeof InternationalRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  PartnersRoute: typeof PartnersRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SettingsRoute: typeof SettingsRoute
  StudentRoute: typeof StudentRoute
  TasksRoute: typeof TasksRoute
  VerificationRoute: typeof VerificationRoute
  ApplicationApplicationIdRoute: typeof ApplicationApplicationIdRoute
  ApplicationStartRoute: typeof ApplicationStartRoute
  EnrollmentEnrollmentIdRoute: typeof EnrollmentEnrollmentIdRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsNewRoute: typeof LeadsNewRoute
  ListsListIdRoute: typeof ListsListIdRoute
  OfferOfferIdRoute: typeof OfferOfferIdRoute
  ProgramsNewRoute: typeof ProgramsNewRoute
  UsersNewRoute: typeof UsersNewRoute
  EnrollmentIndexRoute: typeof EnrollmentIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  ListsIndexRoute: typeof ListsIndexRoute
  OfferIndexRoute: typeof OfferIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor': {
      id: '/counsellor'
      path: '/counsellor'
      fullPath: '/counsellor'
      preLoaderRoute: typeof CounsellorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-settings': {
      id: '/chat-settings'
      path: '/chat-settings'
      fullPath: '/chat-settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acharyawebsite': {
      id: '/acharyawebsite'
      path: '/acharyawebsite'
      fullPath: '/acharyawebsite'
      preLoaderRoute: typeof AcharyawebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/': {
      id: '/offer/'
      path: '/offer'
      fullPath: '/offer/'
      preLoaderRoute: typeof OfferIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment/': {
      id: '/enrollment/'
      path: '/enrollment'
      fullPath: '/enrollment/'
      preLoaderRoute: typeof EnrollmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates/': {
      id: '/email-templates/'
      path: '/'
      fullPath: '/email-templates/'
      preLoaderRoute: typeof EmailTemplatesIndexRouteImport
      parentRoute: typeof EmailTemplatesRoute
    }
    '/automation/': {
      id: '/automation/'
      path: '/'
      fullPath: '/automation/'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/new': {
      id: '/programs/new'
      path: '/programs/new'
      fullPath: '/programs/new'
      preLoaderRoute: typeof ProgramsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$offerId': {
      id: '/offer/$offerId'
      path: '/offer/$offerId'
      fullPath: '/offer/$offerId'
      preLoaderRoute: typeof OfferOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment/$enrollmentId': {
      id: '/enrollment/$enrollmentId'
      path: '/enrollment/$enrollmentId'
      fullPath: '/enrollment/$enrollmentId'
      preLoaderRoute: typeof EnrollmentEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/$automationId': {
      id: '/automation/$automationId'
      path: '/$automationId'
      fullPath: '/automation/$automationId'
      preLoaderRoute: typeof AutomationAutomationIdRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/application/start': {
      id: '/application/start'
      path: '/application/start'
      fullPath: '/application/start'
      preLoaderRoute: typeof ApplicationStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application/$applicationId': {
      id: '/application/$applicationId'
      path: '/application/$applicationId'
      fullPath: '/application/$applicationId'
      preLoaderRoute: typeof ApplicationApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates/create/visual': {
      id: '/email-templates/create/visual'
      path: '/create/visual'
      fullPath: '/email-templates/create/visual'
      preLoaderRoute: typeof EmailTemplatesCreateVisualRouteImport
      parentRoute: typeof EmailTemplatesRoute
    }
    '/email-templates/create/rich-text': {
      id: '/email-templates/create/rich-text'
      path: '/create/rich-text'
      fullPath: '/email-templates/create/rich-text'
      preLoaderRoute: typeof EmailTemplatesCreateRichTextRouteImport
      parentRoute: typeof EmailTemplatesRoute
    }
    '/email-templates/create/plain-text': {
      id: '/email-templates/create/plain-text'
      path: '/create/plain-text'
      fullPath: '/email-templates/create/plain-text'
      preLoaderRoute: typeof EmailTemplatesCreatePlainTextRouteImport
      parentRoute: typeof EmailTemplatesRoute
    }
    '/email-templates/create/html': {
      id: '/email-templates/create/html'
      path: '/create/html'
      fullPath: '/email-templates/create/html'
      preLoaderRoute: typeof EmailTemplatesCreateHtmlRouteImport
      parentRoute: typeof EmailTemplatesRoute
    }
  }
}

interface AutomationRouteChildren {
  AutomationAutomationIdRoute: typeof AutomationAutomationIdRoute
  AutomationIndexRoute: typeof AutomationIndexRoute
}

const AutomationRouteChildren: AutomationRouteChildren = {
  AutomationAutomationIdRoute: AutomationAutomationIdRoute,
  AutomationIndexRoute: AutomationIndexRoute,
}

const AutomationRouteWithChildren = AutomationRoute._addFileChildren(
  AutomationRouteChildren,
)

interface EmailTemplatesRouteChildren {
  EmailTemplatesIndexRoute: typeof EmailTemplatesIndexRoute
  EmailTemplatesCreateHtmlRoute: typeof EmailTemplatesCreateHtmlRoute
  EmailTemplatesCreatePlainTextRoute: typeof EmailTemplatesCreatePlainTextRoute
  EmailTemplatesCreateRichTextRoute: typeof EmailTemplatesCreateRichTextRoute
  EmailTemplatesCreateVisualRoute: typeof EmailTemplatesCreateVisualRoute
}

const EmailTemplatesRouteChildren: EmailTemplatesRouteChildren = {
  EmailTemplatesIndexRoute: EmailTemplatesIndexRoute,
  EmailTemplatesCreateHtmlRoute: EmailTemplatesCreateHtmlRoute,
  EmailTemplatesCreatePlainTextRoute: EmailTemplatesCreatePlainTextRoute,
  EmailTemplatesCreateRichTextRoute: EmailTemplatesCreateRichTextRoute,
  EmailTemplatesCreateVisualRoute: EmailTemplatesCreateVisualRoute,
}

const EmailTemplatesRouteWithChildren = EmailTemplatesRoute._addFileChildren(
  EmailTemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcharyawebsiteRoute: AcharyawebsiteRoute,
  AdmissionsRoute: AdmissionsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApplicationsRoute: ApplicationsRoute,
  AutomationRoute: AutomationRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  CommunicationsRoute: CommunicationsRoute,
  CounsellorRoute: CounsellorRoute,
  DashboardRoute: DashboardRoute,
  DistributionRoute: DistributionRoute,
  EmailTemplatesRoute: EmailTemplatesRouteWithChildren,
  FinanceRoute: FinanceRoute,
  InternationalRoute: InternationalRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  PartnersRoute: PartnersRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SettingsRoute: SettingsRoute,
  StudentRoute: StudentRoute,
  TasksRoute: TasksRoute,
  VerificationRoute: VerificationRoute,
  ApplicationApplicationIdRoute: ApplicationApplicationIdRoute,
  ApplicationStartRoute: ApplicationStartRoute,
  EnrollmentEnrollmentIdRoute: EnrollmentEnrollmentIdRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsNewRoute: LeadsNewRoute,
  ListsListIdRoute: ListsListIdRoute,
  OfferOfferIdRoute: OfferOfferIdRoute,
  ProgramsNewRoute: ProgramsNewRoute,
  UsersNewRoute: UsersNewRoute,
  EnrollmentIndexRoute: EnrollmentIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  ListsIndexRoute: ListsIndexRoute,
  OfferIndexRoute: OfferIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
